// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __Writer_hh__
#define __Writer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Writer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Writer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Writer
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE Writer

_CORBA_MODULE_BEG

#ifndef __Writer_mmWriter__
#define __Writer_mmWriter__

  class mWriter;
  class _objref_mWriter;
  class _impl_mWriter;
  
  typedef _objref_mWriter* mWriter_ptr;
  typedef mWriter_ptr mWriterRef;

  class mWriter_Helper {
  public:
    typedef mWriter_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_mWriter, mWriter_Helper> mWriter_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_mWriter,mWriter_Helper > mWriter_out;

#endif

  // interface mWriter
  class mWriter {
  public:
    // Declarations for this interface type.
    typedef mWriter_ptr _ptr_type;
    typedef mWriter_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_mWriter :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Float oCurrentCursorPositionX();
    ::CORBA::Float oCurrentCursorPositionY();
    void gotoStart(::CORBA::Boolean sel);
    void gotoEnd(::CORBA::Boolean sel);
    void gotoStartOfLine(::CORBA::Boolean sel);
    void gotoEndOfLine(::CORBA::Boolean sel);

    inline _objref_mWriter()  { _PR_setobj(0); }  // nil
    _objref_mWriter(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_mWriter();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_mWriter(const _objref_mWriter&);
    _objref_mWriter& operator = (const _objref_mWriter&);
    // not implemented

    friend class mWriter;
  };

  class _pof_mWriter : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_mWriter() : _OMNI_NS(proxyObjectFactory)(mWriter::_PD_repoId) {}
    virtual ~_pof_mWriter();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_mWriter :
    public virtual omniServant
  {
  public:
    virtual ~_impl_mWriter();

    virtual ::CORBA::Float oCurrentCursorPositionX() = 0;
    virtual ::CORBA::Float oCurrentCursorPositionY() = 0;
    virtual void gotoStart(::CORBA::Boolean sel) = 0;
    virtual void gotoEnd(::CORBA::Boolean sel) = 0;
    virtual void gotoStartOfLine(::CORBA::Boolean sel) = 0;
    virtual void gotoEndOfLine(::CORBA::Boolean sel) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_mWriter;

_CORBA_MODULE_END



_CORBA_MODULE POA_Writer
_CORBA_MODULE_BEG

  class mWriter :
    public virtual Writer::_impl_mWriter,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~mWriter();

    inline ::Writer::mWriter_ptr _this() {
      return (::Writer::mWriter_ptr) _do_this(::Writer::mWriter::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_Writer
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, Writer::mWriter_ptr _s);
void operator<<=(::CORBA::Any& _a, Writer::mWriter_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, Writer::mWriter_ptr& _s);



inline void
Writer::mWriter::_marshalObjRef(::Writer::mWriter_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Writer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Writer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Writer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Writer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Writer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Writer
#endif

#endif  // __Writer_hh__

